Ocean Cubes
deepesdl/cube-gen pull request #19
Opened 2023-02-11 15:21 UTC by davemlz

2023-02-16 09:26 UTC, AliceBalfanz commented on Ocean/README.md
> +Information dedicated to the generation of the Ocean Datacubes. In this folder two ocean data cubes were created: 1) The Particulate Organic Carbon (POC) Data Cube at 4 km and 2) the Oceanic Export P
```suggestion
Information dedicated to the generation of the Ocean Datacubes. In this folder two ocean data cubes were created:   
1) The Particulate Organic Carbon (POC) Data Cube at 4 km and   
2) the Oceanic Export Production, Phytoplankton Carbon and Primary Production Data Cube at 9 km.
```

2023-02-16 10:24 UTC, AliceBalfanz commented on Ocean/README.md
> +download-sources-4km.py
```suggestion
cd inputs-collect/
python download-sources-4km.py
```

2023-02-16 10:25 UTC, AliceBalfanz commented on Ocean/README.md
> +To download the datasets, it is required to run the following files:
Please add a description, that deep-esdl-cube-gen python env needs to be used for executing the scripts. And how to do this.

2023-02-16 10:26 UTC, AliceBalfanz commented on Ocean/README.md
> +download-sources-9km.py
```suggestion
python download-sources-9km.py
```

2023-02-16 10:35 UTC, AliceBalfanz commented on Ocean/inputs-collect/download-sources-9km.py
> +    print(f"Downloaidng files...")
```suggestion
    print(f"Downloading files...")
```

2023-02-16 11:18 UTC, AliceBalfanz commented on Ocean/inputs-collect/download-sources-4km.py
> +    print(f"Downloaidng files...")
```suggestion
    print(f"Downloading files...")
```

2023-02-16 12:54 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/oceanic-export-production-to-zarr.py # Convert files to zarr
```suggestion
cd ..
python inputs-preprocess/oceanic-export-production-to-zarr.py # Convert files to zarr
```

2023-02-16 12:55 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/oceanic-export-production-to-s3.py # Upload full cube to the s3 bucket
```suggestion
python inputs-preprocess/oceanic-export-production-to-s3.py # Upload full cube to the s3 bucket
```

2023-02-16 12:55 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/particulate-organic-carbon-to-zarr.py # Convert files to zarr
```suggestion
python inputs-preprocess/particulate-organic-carbon-to-zarr.py # Convert files to zarr
```

2023-02-16 12:55 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/phytoplankton-carbon-to-zarr.py # Convert files to zarr
```suggestion
python inputs-preprocess/phytoplankton-carbon-to-zarr.py # Convert files to zarr
```

2023-02-16 12:56 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/phytoplankton-carbon-to-s3.py # Upload full cube to the s3 bucket
```suggestion
python inputs-preprocess/phytoplankton-carbon-to-s3.py # Upload full cube to the s3 bucket
```

2023-02-16 12:56 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/primary-production-to-zarr.py # Convert files to zarr
```suggestion
python inputs-preprocess/primary-production-to-zarr.py # Convert files to zarr
```

2023-02-16 12:56 UTC, AliceBalfanz commented on Ocean/README.md
> +inputs-preprocess/primary-production-to-s3.py # Upload full cube to the s3 bucket
```suggestion
python inputs-preprocess/primary-production-to-s3.py # Upload full cube to the s3 bucket
```

2023-02-16 12:56 UTC, AliceBalfanz commented on Ocean/README.md
> +output-merge/merge-4km.py
```suggestion
python output-merge/merge-4km.py
```

2023-02-16 12:56 UTC, AliceBalfanz commented on Ocean/README.md
> +output-merge/merge-9km.py
```suggestion
python output-merge/merge-9km.py
```

2023-02-26 15:45 UTC, davemlz commented on Ocean/README.md
> +### 2. Preprocessing datasets
I required to convert each one of them into zarr first (multiple nc files per dataset to zarr). That's why they're saved first as multiple zarr and then concatenated and uploaded to s3 directly.

2023-03-08 09:06 UTC, AliceBalfanz commented on Ocean/README.md
> +### 2. Preprocessing datasets
But this could also be done in S3 - you could write the zarrs into s3 and then concatenate them using the data saved to s3

2023-03-08 09:11 UTC, AliceBalfanz commented on Ocean/cube4km.geojson
> +                    "color_value_min": null,
https://github.com/deepesdl/dataset-spec/tree/main/dataset-spec#data-variable---metadata

> f `color_value_min`, `color_value_max` are given, their values should be numbers, not null

2023-03-08 09:12 UTC, AliceBalfanz commented on Ocean/cube4km.geojson
> +                "valid_min": null,
https://github.com/deepesdl/dataset-spec/tree/main/dataset-spec#data-variable---general

> If valid_min, valid_max are given, their values should be numbers, not null. Same applies to the value items of valid_range.

Please apply this for all occurences.

2023-03-08 09:13 UTC, AliceBalfanz requested changes
Please see my comments.

2023-03-18 12:35 UTC, davemlz commented on Ocean/README.md
> +### 2. Preprocessing datasets
Ok, next time we do it like this :)

2023-03-18 13:28 UTC, davemlz commented on Ocean/cube4km.geojson
> +                    "color_value_min": null,
I decided to delete this attribute as it's optional.

2023-03-18 13:28 UTC, davemlz commented on Ocean/cube4km.geojson
> +                "valid_min": null,
I decided to delete these attributes also as they are optional.

2023-03-28 14:33 UTC, AliceBalfanz commented on Ocean/README.md
> +Information dedicated to the generation of the Ocean Datacubes. In this folder two ocean data cubes were created:
```suggestion
Information dedicated to the generation of the Ocean Datacubes. By using the following recipe two ocean data cubes can be reproduced:
```

2023-03-28 14:34 UTC, AliceBalfanz commented on Ocean/README.md
> +The total storage required for the generation of this cube is 490 Gb.
```suggestion
The total storage required for the generation of these cube is 490 Gb.
```

2023-04-04 12:19 UTC, AliceBalfanz commented on Ocean/README.md
> +The raw data is preprocessed in order to create a single input `.zarr` cube per dataset. The preprocessing steps might involve time resampling and/or spatial resampling according to the dataset. The
```suggestion
The raw data is preprocessed in order to create a single input `.zarr` cube per dataset. The preprocessing steps might involve time resampling and/or spatial resampling according to the dataset. The preprocessing code for each dataset is found at the `inputs-preprocess` folder. Note that some datasets have multiple parts according to the preprocessing steps that were applied:

**If you wish to execute the below scripts please ensure to adjust the `root` parameter in the scripts to point to a s3 bucket which you have read-write access to.**
```

2023-04-04 12:25 UTC, AliceBalfanz commented on Ocean/README.md
> +```
```suggestion
```

**If you wish to execute the above script please ensure to adjust the s3 bucket path to point to the bucket which you have read-write access to.**
```

2023-04-04 12:27 UTC, AliceBalfanz commented on Ocean/README.md
> +```
It does not work well with the inline comment here. Could you please add: 

**If you wish to execute the above script please ensure to adjust the s3 bucket path to point to the bucket which you have read-write access to.**

2023-04-05 10:46 UTC, davemlz commented
Thank you for the review, Alicja! I'm running the latest requests by Javier. So I will update this PR today when I finish them and then merge it.

2023-04-05 20:06 UTC, davemlz commented
I just updated the code and the recipe. I'm merging the branch :)

2023-04-05 20:06 UTC, merged